package com.example.multimodulecrypto.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF0042A9)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0063F5)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF445C9B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFABC0FF)
val onSecondaryContainerLight = Color(0xFF122F6C)
val tertiaryLight = Color(0xFF7B019F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA53DC7)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B24)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B24)
val surfaceVariantLight = Color(0xFFDEE2F4)
val onSurfaceVariantLight = Color(0xFF424655)
val outlineLight = Color(0xFF727687)
val outlineVariantLight = Color(0xFFC2C6D8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3039)
val inverseOnSurfaceLight = Color(0xFFEFF0FC)
val inversePrimaryLight = Color(0xFFB2C5FF)
val surfaceDimLight = Color(0xFFD8D9E5)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FF)
val surfaceContainerLight = Color(0xFFECEDF9)
val surfaceContainerHighLight = Color(0xFFE7E7F4)
val surfaceContainerHighestLight = Color(0xFFE1E2EE)
