package com.example.multimodulecrypto.core.model

import com.google.gson.annotations.SerializedName


data class CurrentPrice (

  @SerializedName("aed"  ) var aed  : Int?    = null,
  @SerializedName("ars"  ) var ars  : Int?    = null,
  @SerializedName("aud"  ) var aud  : Int?    = null,
  @SerializedName("bch"  ) var bch  : Double? = null,
  @SerializedName("bdt"  ) var bdt  : Int?    = null,
  @SerializedName("bhd"  ) var bhd  : Int?    = null,
  @SerializedName("bmd"  ) var bmd  : Int?    = null,
  @SerializedName("bnb"  ) var bnb  : Double? = null,
  @SerializedName("brl"  ) var brl  : Int?    = null,
  @SerializedName("btc"  ) var btc  : Int?    = null,
  @SerializedName("cad"  ) var cad  : Int?    = null,
  @SerializedName("chf"  ) var chf  : Int?    = null,
  @SerializedName("clp"  ) var clp  : Int?    = null,
  @SerializedName("cny"  ) var cny  : Int?    = null,
  @SerializedName("czk"  ) var czk  : Int?    = null,
  @SerializedName("dkk"  ) var dkk  : Int?    = null,
  @SerializedName("dot"  ) var dot  : Int?    = null,
  @SerializedName("eos"  ) var eos  : Int?    = null,
  @SerializedName("eth"  ) var eth  : Double? = null,
  @SerializedName("eur"  ) var eur  : Int?    = null,
  @SerializedName("gbp"  ) var gbp  : Int?    = null,
  @SerializedName("gel"  ) var gel  : Int?    = null,
  @SerializedName("hkd"  ) var hkd  : Int?    = null,
  @SerializedName("huf"  ) var huf  : Int?    = null,
  @SerializedName("idr"  ) var idr  : Int?    = null,
  @SerializedName("ils"  ) var ils  : Int?    = null,
  @SerializedName("inr"  ) var inr  : Int?    = null,
  @SerializedName("jpy"  ) var jpy  : Int?    = null,
  @SerializedName("krw"  ) var krw  : Int?    = null,
  @SerializedName("kwd"  ) var kwd  : Double? = null,
  @SerializedName("lkr"  ) var lkr  : Int?    = null,
  @SerializedName("ltc"  ) var ltc  : Double? = null,
  @SerializedName("mmk"  ) var mmk  : Int?    = null,
  @SerializedName("mxn"  ) var mxn  : Int?    = null,
  @SerializedName("myr"  ) var myr  : Int?    = null,
  @SerializedName("ngn"  ) var ngn  : Int?    = null,
  @SerializedName("nok"  ) var nok  : Int?    = null,
  @SerializedName("nzd"  ) var nzd  : Int?    = null,
  @SerializedName("php"  ) var php  : Int?    = null,
  @SerializedName("pkr"  ) var pkr  : Int?    = null,
  @SerializedName("pln"  ) var pln  : Int?    = null,
  @SerializedName("rub"  ) var rub  : Int?    = null,
  @SerializedName("sar"  ) var sar  : Int?    = null,
  @SerializedName("sek"  ) var sek  : Int?    = null,
  @SerializedName("sgd"  ) var sgd  : Int?    = null,
  @SerializedName("thb"  ) var thb  : Int?    = null,
  @SerializedName("twd"  ) var twd  : Int?    = null,
  @SerializedName("uah"  ) var uah  : Int?    = null,
  @SerializedName("usd"  ) var usd  : Int?    = null,
  @SerializedName("vef"  ) var vef  : Double? = null,
  @SerializedName("vnd"  ) var vnd  : Int?    = null,
  @SerializedName("xag"  ) var xag  : Double? = null,
  @SerializedName("xau"  ) var xau  : Double? = null,
  @SerializedName("xdr"  ) var xdr  : Int?    = null,
  @SerializedName("xlm"  ) var xlm  : Int?    = null,
  @SerializedName("xrp"  ) var xrp  : Int?    = null,
  @SerializedName("yfi"  ) var yfi  : Double? = null,
  @SerializedName("zar"  ) var zar  : Int?    = null,
  @SerializedName("bits" ) var bits : Int?    = null,
  @SerializedName("link" ) var link : Int?    = null,
  @SerializedName("sats" ) var sats : Int?    = null

)